version: 2.1

orbs:
  node: circleci/node@3.0.1

jobs:
  test:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          working_directory: ~/project/app
          name: Test
          command: npm test  
      - persist_to_workspace:
          root: .
          paths:
            -  /temp/app
      - run:
          working_directory: ~/project/app
          command: ls      
  build:
    docker:
      - image: cimg/node:current
    steps:
      - attach_workspace:
          at: /temp/app
      - run:
          working_directory: ~/project/app
          command: ls
      - run:
          working_directory: ~/project/app
          command: npm install
      - run:
          working_directory: ~/project/app
          command: npm start
#    - save_caches:
#        paths:
#          - ~/project/app
#        keys: dependencies-{{ checksum "package.json" }}
#  deploy:
#    docker:
#       - image: cimg/node:current
#     steps:
#      - restore_caches:
#          keys:
#          - dependencies-{{ checksum "package.json" }}
#      - run:
#          command: npm start
workflows:
  build_and_test:
    jobs:
      - test
      - build
    #  - deploy:
    #     requires:
    #        - build
