version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          working_directory: ~/project/app
          name: Test
          command: npm test  
      - run:
          working_directory: ~/project/app
          command: ls
      - run:
          working_directory: ~/project/app
          command: pwd        
  build:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          working_directory: ~/project/app
          command: pwd    
      - run:
          working_directory: ~/project/app
          command: npm install
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  build_image:
      docker:
        - image: cimg/node:current
      steps:
        - setup_remote_docker
        - attach_workspace:
            at: .
        - run:
            working_directory: ~/project
            command: | 
              docker build -t ghcr.io/aleciofrjr/devops-teste:${CIRCLE_SHA1} .
        - run:
            name: tag image
              command: docker tag ghcr.io/aleciofrjr/devops-teste:${CIRCLE_SHA1} ghcr.io/aleciofrjr/devops-teste:latest
        # push no git verificar documentação git
        - run:
            name: authenticate github package
            command: docker login ghcr.io -u aleciofrjr --password ${GIT_HUB_PACKAGES}
        - run:
            name: push docker image
            command: docker push ghcr.io/aleciofrjr/devops-teste --all-tags
        - persist_to_workspace:
            root: .
            paths:
              - '*' 
  deploy:
      docker:
       - image: cimg/node:current
      steps:
      - attach_workspace:
            at: .
      - run:
          working_directory: ~/project/app
          command: npm start
workflows:
  build_and_test:
    jobs:
      - test
      - build:
          requires:
          - test
      - build_image:
          requires:
            - build
      - deploy:
         requires:
            - build_image
            
