version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: fake Test
          working_directory: ~/project/app
          command: npm test     
  build:
    docker:
      - image: cimg/node:current
    steps:
      - checkout    
      - run:
          name: install devDependencies
          working_directory: ~/project/app
          command: npm install
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  build_image:
      docker:
        - image: cimg/node:current
      steps:
        - setup_remote_docker
        - attach_workspace:
            at: .
        - run:
            name: build image
            working_directory: ~/project
            command: | 
              docker build -t ghcr.io/aleciofrjr/devops-teste:${CIRCLE_SHA1} .
        - run:
            name: tag image
            command: docker tag ghcr.io/aleciofrjr/devops-teste:${CIRCLE_SHA1} ghcr.io/aleciofrjr/devops-teste:latest
        - run:
            name: authenticate github package
            command: docker login ghcr.io -u aleciofrjr --password ${GIT_HUB_PKGS}
        - run:
            name: push docker image
            command: docker push ghcr.io/aleciofrjr/devops-teste --all-tags
        - persist_to_workspace:
            root: .
            paths:
              - '*' 
  deploy:
      docker:
       - image: hashicorp/terraform:0.14.11
      steps:
      - attach_workspace:
            at: .
      - run:
          name: terraform init
          working_directory: ~/project/app
          command: |
            cd ~/devops-teste
            cd ~/devops-teste
            terraform init
      - run:
          name: terraform apply
          command: |
            cd ~/devops-teste
            terraform apply --auto-approve  
      - run:
          name: authenticate instance EC2 in github package
          working_directory: ~/project/app
          command:  ssh -o StrictHostKeyChecking=no ubuntu@${outputs.tf} "sudo docker login ghcr.io -u aleciofrjr --password ${GIT_HUB_PKGS}"
      - run:
          name: Execute docker-compose
          command: ssh -o StrictHostKeyChecking=no ubuntu@${outputs.tf} "cd devops-teste && sudo docker-compose up"
workflows:
  build_and_test:
    jobs:
      - test
      - build:
          requires:
          - test
      - build_image:
          requires:
            - build
      - deploy:
         requires:
            - build_image
            
