version: 2.1

orbs:
  node: circleci/node@3.0.1

jobs:
  test:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          working_directory: ~/project/app
          name: Test
          command: npm test  
      - run:
          working_directory: ~/project/app
          command: ls
      - run:
          working_directory: ~/project/app
          command: pwd        
  build:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          working_directory: ~/project/app
          command: pwd    
      - run:
          working_directory: ~/project/app
          command: npm install
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  build_image:
      docker:
        - image: cimg/node:current
      steps:
        - attach_workspace:
            at: .
        - run:
            working_directory: ~/project
            command: | 
              docker build -t ghcr.io/OWNER/devops-teste:${CICLE_SHA1} .
        - persist_to_workspace:
            root: .
            paths:
              - '*' 
  deploy:
      docker:
       - image: cimg/node:current
      steps:
      - attach_workspace:
            at: .
      - run:
          working_directory: ~/project/app
          command: npm start
workflows:
  build_and_test:
    jobs:
      - test
      - build
      - deploy:
         requires:
            - build
