version: 1.0

orbs:
  node: circleci/node@3.0.1

jobs:
  test:
    docker:
      - image: cimg/node:current
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Test
          command: npm test
  # deploy:
  #   docker:
  #     - image: cimg/node:current
  #   steps:
  #     - attach_workspace:
  #         at: ~/app
  #     - run:
  #         name: deploy
  #         command: npm start
workflows:
  version: 1.0
  build_and_test:
    jobs:
      - test:
          requires:
            - teste
            # - deploy
